name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      env:
        IMAGE_NAME: ${{ secrets.REGISTRY_USERNAME }}/c_c_s:${{ github.ref_name }}
      run: |
        docker build -t $IMAGE_NAME .
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker push $IMAGE_NAME
